# Generated by Django 2.1.7 on 2019-04-05 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
