# Generated by Django 2.1.7 on 2019-04-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaboard', '0002_auto_20190405_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans', to='qaboard.Question'),
        ),
    ]
