# Generated by Django 2.1.7 on 2019-04-06 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qaboard', '0003_auto_20190405_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='ans_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
