# Generated by Django 2.1.7 on 2019-04-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qaboard', '0004_answer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='quest_key',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
