# Generated by Django 2.1.7 on 2019-04-06 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qaboard', '0005_auto_20190406_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_upvote', models.BooleanField(default=False)),
                ('if_downvote', models.BooleanField(default=False)),
                ('quest_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='qaboard.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
