# Generated by Django 2.1.7 on 2019-04-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qaboard', '0007_answer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
    ]
